FROM node:20-alpine
WORKDIR /app
# Copiamos solo los archivos de dependencias primero para aprovechar el caché
COPY package*.json ./
RUN npm install
# Copiamos el resto del código
COPY . .
# Corremos el script de desarrollo que Nest ya trae por defecto
CMD ["npm", "run", "start:dev"]