export const SERVICE_TOKEN = {
  DAOS: {
    GET_SERVICE: 'GET_SERVICE_DAO',
    UPDATE_SERVICE_DAO: 'UPDATE_SERVICE_DAO',
    CREATE_SERVICE_DAO: 'CREATE_SERVICE_DAO',
    DELETE_SERVICE_DAO: 'DELETE_SERVICE_DAO',
    GET_SEASON_SERVICE: 'GET_SEASON_SERVICE_DAO',
    GET_SERVICES: 'GET_SERVICES_DAO',
  },
  USECASE: {
    GET_SERVICE: 'GET_SERVICE_USECASE',
    CREATE_SERVICE: 'CREATE_SERVICE_USECASE',
    UPDATE_SERVICE: 'UPDATE_SERVICE_USECASE',
    DELETE_SERVICE: 'DELETE_SERVICE_USECASE',
    GET_SEASON_SERVICE: 'GET_SEASON_SERVICE_USECASE',
    GET_SERVICES: 'GET_SERVICES_USECASE',
  },
};
