export const SEASON_TOKEN = {
  DAOS: {
    GET_SEASON: 'GET_SEASON_DAO',
    UPDATE_SEASON_DAO: 'UPDATE_SEASON_DAO',
    CREATE_SEASON_DAO: 'CREATE_SEASON_DAO',
    DELETE_SEASON_DAO: 'DELETE_SEASON_DAO',
    GET_HISTORY: 'GET_HISTORY_DAO',
    CURRENT_SEASON_DAO: 'CURRENT_SEASON_DAO',
    SET_ACTIVE: 'SET_ACTIVE_SEASON',
    CLONE_SEASON: 'CLONE_SEASON',
    GET_SEASON_DATA: 'GET_SEASON_DATA',
    GET_ACTIVE: 'GET_ACTIVE',

    SEARCHER: 'SEASON_SEARCHER_DAO',
  },
  USECASE: {
    GET_SEASON: 'GET_SEASON_USECASE',
    CREATE_SEASON: 'CREATE_SEASON_USECASE',
    UPDATE_SEASON: 'UPDATE_SEASON_USECASE',
    DELETE_SEASON: 'DELETE_SEASON_USECASE',
    CURRENT_SEASON: 'CURRENT_SEASON',
    SET_ACTIVE: 'SET_ACTIVE_SEASON',
    CLONE_SEASON: 'CLONE_SEASON',
    GET_SEASON_DATA: 'GET_SEASON_DATA',
    GET_HISTORY: 'GET_HISTORY',
    GET_ACTIVE: 'GET_ACTIVE',
    SEARCHER: 'SEASON_SEARCHER',
  },
};
