export const RESERVATION_TOKEN = {
  DAOS: {
    GET_RESERVATION: 'GET_RESERVATION_DAO',
    UPDATE_RESERVATION_DAO: 'UPDATE_RESERVATION_DAO',
    CREATE_RESERVATION_DAO: 'CREATE_RESERVATION_DAO',
    DELETE_RESERVATION_DAO: 'DELETE_RESERVATION_DAO',
    GET_SEASON_RESERVATION: 'GET_SEASON_RESERVATION_DAO',
    GET_DETAILS: 'GET_DETAILS_DAO',
    GET_CURRENT: 'GET_CURRENT_DAO',
  },
  USECASE: {
    GET_RESERVATION: 'GET_RESERVATION_USECASE',
    CREATE_RESERVATION: 'CREATE_RESERVATION_USECASE',
    UPDATE_RESERVATION: 'UPDATE_RESERVATION_USECASE',
    DELETE_RESERVATION: 'DELETE_RESERVATION_USECASE',
    GET_DETAILS: 'GET_DETAILS_USECASE',
    GET_SEASON_RESERVATIONS: 'GET_SEASON_RESERVATION_USECASE',
    GET_CURRENT: 'GET_CURRENT_USECASE',
  },
};
