export const SHADOW_TOKEN = {
  DAOS: {
    GET_SHADOW: 'GET_SHADOW_DAO',
    UPDATE_SHADOW_DAO: 'UPDATE_SHADOW_DAO',
    CREATE_SHADOW_DAO: 'CREATE_SHADOW_DAO',
    DELETE_SHADOW_DAO: 'DELETE_SHADOW_DAO',
    SHADOW_MAP: 'SHADOW_MAP',
    SEARCHER: 'SHADOW_SEARCHER_DAO',
    SHADOW_DETAILS: 'SHADOW_DETAILS',
  },
  USECASE: {
    GET_SHADOW: 'GET_SHADOW_USECASE',
    CREATE_SHADOW: 'CREATE_SHADOW_USECASE',
    UPDATE_SHADOW: 'UPDATE_SHADOW_USECASE',
    DELETE_SHADOW: 'DELETE_SHADOW_USECASE',
    GET_SHADOW_HISTORY: 'GET_SHADOW_HISTORY_USECASE',
    GET_SHADOW_DETAILS: 'GET_SHADOW_DETAILS',
    GET_SHADOW_MAP: 'GET_SHADOW_MAP',
    SEARCHER: 'SHADOW_SEARCHER',
  },
};
