export const CLIENT_TOKEN = {
  DAOS: {
    GET_CLIENT: 'GET_CLIENT_DAO',
    UPDATE_CLIENT_DAO: 'UPDATE_CLIENT_DAO',
    CREATE_CLIENT_DAO: 'CREATE_CLIENT_DAO',
    DELETE_CLIENT_DAO: 'DELETE_CLIENT_DAO',
    SEARCHER: 'CLIENT_SEARCHER_DAO',
    CLIENT_DETAILS: 'CLIENT_DETAILS_DAO',
    CLIENT_LIST: 'CLIENT_LIST_DAO',
  },
  USECASE: {
    GET_CLIENT: 'GET_CLIENT_USECASE',
    CREATE_CLIENT: 'CREATE_CLIENT_USECASE',
    UPDATE_CLIENT: 'UPDATE_CLIENT_USECASE',
    DELETE_CLIENT: 'DELETE_CLIENT_USECASE',
    SEARCHER: 'CLIENT_SEARCHER',
    CLIENT_DETAILS: 'CLIENT_DETAILS',
    CLIENT_LIST: 'CLIENT_LIST',
  },
};
