export const INVOICE_TOKEN = {
  DAOS: {
    GET_INVOICE: 'GET_INVOICE_DAO',
    DELETE_INVOICE_DAO: 'DELETE_INVOICE_DAO',
    INVOICE_DETAILS: 'INVOICE_DETAILS_DAO',
    INVOICE_LIST: 'INVOICE_LIST_DAO',
  },
  USECASE: {
    GET_INVOICE: 'GET_INVOICE_USECASE',
    DELETE_INVOICE: 'DELETE_INVOICE_USECASE',
    INVOICE_DETAILS: 'INVOICE_DETAILS',
    INVOICE_LIST: 'INVOICE_LIST',
  },
};
