export const INVOICE_TOKEN = {
  DAOS: {
    GET_INVOICE: 'GET_INVOICE_DAO',
    DELETE_INVOICE_DAO: 'DELETE_INVOICE_DAO',
    INVOICE_DETAILS: 'INVOICE_DETAILS_DAO',
    INVOICE_LIST: 'INVOICE_LIST_DAO',
    INVOICE_ITEM_UPDATE: 'INVOICE_ITEM_UPDATE_DAO',
    INVOICE_ITEM_DELETE: 'INVOICE_ITEM_DELETE_DAO',

    SEARCHER: 'INVOICE_SEARCHER_DAO',
  },
  USECASE: {
    GET_INVOICE: 'GET_INVOICE_USECASE',
    DELETE_INVOICE: 'DELETE_INVOICE_USECASE',
    INVOICE_DETAILS: 'INVOICE_DETAILS',
    INVOICE_LIST: 'INVOICE_LIST',
    INVOICE_ITEM_UPDATE: 'INVOICE_ITEM_UPDATE',
    INVOICE_ITEM_DELETE: 'INVOICE_ITEM_DELETE',
    SEARCHER: 'INVOICE_SEARCHER',
  },
};
