export const PAYMENT_TOKEN = {
  DAOS: {
    GET_PAYMENT: 'GET_PAYMENT_DAO',
    CREATE_PAYMENT_DAO: 'CREATE_PAYMENT_DAO',
    DELETE_PAYMENT_DAO: 'DELETE_PAYMENT_DAO',
    PAYMENT_REPORT: 'PAYMENT_REPORT_DAO',
  },
  USECASE: {
    GET_PAYMENT: 'GET_PAYMENT_USECASE',
    CREATE_PAYMENT: 'CREATE_PAYMENT_USECASE',
    DELETE_PAYMENT: 'DELETE_PAYMENT_USECASE',
    REPORT: 'PAYMENT_REPORT',
    EXPORT_REPORT: 'EXPORT_REPORT',
  },
  STRATEGY: {
    FACTORY: 'REPORT_STRATEGY_FACTORY',
  }
};
